/** Schéma SQLite — équivalent fonctionnel au schéma MySQL. */

export const SQLITE_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_type TEXT NOT NULL CHECK (user_type IN ('admin', 'internal', 'public')),
    username TEXT,
    email TEXT,
    external_ref TEXT,
    display_name TEXT,
    created_by_username TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT,
    UNIQUE (user_type, email)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)`,
  `CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`,
  `CREATE TABLE IF NOT EXISTS iso_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    system_family TEXT,
    distribution TEXT,
    edition TEXT,
    version_track TEXT,
    architecture TEXT DEFAULT 'amd64',
    file_type TEXT DEFAULT 'iso',
    description TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    is_public INTEGER NOT NULL DEFAULT 1,
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_iso_distribution ON iso_items(distribution)`,
  `CREATE INDEX IF NOT EXISTS idx_iso_enabled ON iso_items(enabled)`,
  `CREATE TABLE IF NOT EXISTS iso_sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    iso_item_id INTEGER NOT NULL REFERENCES iso_items(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    protocol TEXT NOT NULL CHECK (protocol IN ('http', 'https', 'ftp')),
    url TEXT NOT NULL,
    allow_insecure_tls INTEGER NOT NULL DEFAULT 0,
    ftp_passive INTEGER NOT NULL DEFAULT 1,
    match_regex TEXT NOT NULL,
    version_regex TEXT,
    checksum_regex TEXT,
    discovery_enabled INTEGER NOT NULL DEFAULT 0,
    discovery_depth INTEGER NOT NULL DEFAULT 0,
    discovery_regex TEXT,
    priority INTEGER NOT NULL DEFAULT 100,
    enabled INTEGER NOT NULL DEFAULT 1,
    last_status TEXT NOT NULL DEFAULT 'never',
    last_error TEXT,
    last_checked_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sources_iso ON iso_sources(iso_item_id)`,
  `CREATE TABLE IF NOT EXISTS iso_releases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    iso_item_id INTEGER NOT NULL REFERENCES iso_items(id) ON DELETE CASCADE,
    source_id INTEGER REFERENCES iso_sources(id) ON DELETE SET NULL,
    version TEXT,
    filename TEXT NOT NULL,
    url TEXT NOT NULL,
    checksum_url TEXT,
    checksum_sha256 TEXT,
    file_size INTEGER,
    published_at TEXT,
    detected_at TEXT NOT NULL DEFAULT (datetime('now')),
    is_latest INTEGER NOT NULL DEFAULT 0,
    raw_metadata TEXT,
    local_path TEXT,
    download_status TEXT NOT NULL DEFAULT 'none',
    local_downloaded_at TEXT,
    UNIQUE (iso_item_id, filename)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_releases_latest ON iso_releases(iso_item_id, is_latest)`,
  `CREATE TABLE IF NOT EXISTS destinations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    destination_type TEXT NOT NULL,
    label TEXT,
    target TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    config TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    iso_item_id INTEGER NOT NULL REFERENCES iso_items(id) ON DELETE CASCADE,
    enabled INTEGER NOT NULL DEFAULT 1,
    notify_mode TEXT NOT NULL DEFAULT 'immediate',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT,
    UNIQUE (user_id, iso_item_id)
  )`,
  `CREATE TABLE IF NOT EXISTS scan_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trigger_type TEXT NOT NULL,
    triggered_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'running',
    started_at TEXT NOT NULL DEFAULT (datetime('now')),
    finished_at TEXT,
    checked_sources INTEGER NOT NULL DEFAULT 0,
    found_releases INTEGER NOT NULL DEFAULT 0,
    new_releases INTEGER NOT NULL DEFAULT 0,
    total_sources INTEGER NOT NULL DEFAULT 0,
    completed_sources INTEGER NOT NULL DEFAULT 0,
    notify_enabled INTEGER NOT NULL DEFAULT 1,
    context_json TEXT,
    duration_ms INTEGER,
    error_message TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS scan_run_sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scan_run_id INTEGER NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    source_id INTEGER NOT NULL,
    iso_item_id INTEGER NOT NULL,
    iso_name TEXT,
    source_name TEXT,
    source_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    started_at TEXT,
    finished_at TEXT,
    duration_ms INTEGER,
    matches_found INTEGER NOT NULL DEFAULT 0,
    new_releases INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    discovery_json TEXT,
    log_excerpt TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS scan_run_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scan_run_id INTEGER NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    level TEXT NOT NULL DEFAULT 'info',
    category TEXT NOT NULL DEFAULT 'general',
    message TEXT NOT NULL,
    context_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS notification_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    iso_release_id INTEGER NOT NULL REFERENCES iso_releases(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL DEFAULT 'new_release',
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS notification_deliveries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    notification_event_id INTEGER NOT NULL REFERENCES notification_events(id) ON DELETE CASCADE,
    destination_id INTEGER NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    scheduled_for TEXT NOT NULL DEFAULT (datetime('now')),
    digest_bucket TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TEXT,
    next_retry_at TEXT,
    response_code INTEGER,
    response_body TEXT,
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`
];

export const SQLITE_MIGRATIONS = [
  `ALTER TABLE iso_releases ADD COLUMN local_path TEXT`,
  `ALTER TABLE iso_releases ADD COLUMN download_status TEXT NOT NULL DEFAULT 'none'`,
  `ALTER TABLE iso_releases ADD COLUMN local_downloaded_at TEXT`,
  `ALTER TABLE iso_items ADD COLUMN catalog_preset_id TEXT`,
  `ALTER TABLE iso_items ADD COLUMN catalog_source TEXT`,
  `ALTER TABLE iso_sources ADD COLUMN catalog_preset_id TEXT`,
  `ALTER TABLE iso_sources ADD COLUMN catalog_source_key TEXT`,
  `ALTER TABLE iso_sources ADD COLUMN catalog_source TEXT`
];
